In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr + 2)
print(arr * 3)
print(arr / 2)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [22]:
arr1=np.array([1,2,3,6,4,5])
reversed=arr1[::-1]
print(reversed)


[5 4 6 3 2 1]


In [23]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
unique_elements, counts= np.unique(arr,return_counts=True)
m1=np.argmax(counts)
m2=unique_elements[m1]
m2

np.int64(1)

In [24]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
unique_elements, counts=np.unique(arr,return_counts=True)
m1=np.argmax(counts)
m2=unique_elements[m1]
m2


np.int64(1)

In [25]:
arr=np.array([[10,20,30], [40,50,60], [70,80,90]])
a=arr[0,1]
print(a)
arr=np.array([[10,20,30], [40,50,60], [70,80,90]])
b=arr[2,0]
print(b)


20
70


In [26]:
import numpy as np
y=np.linspace(10,100,25)
print(y)

dim=y.ndim
print("Dimenions of the array: ", dim)

shape=y.shape
print("Shape of the array: ", shape)

tot=y.size
print("Total elements in the array:",tot)

data=y.dtype
print("Data type: ", data)

b=y.nbytes
print("Total number of bytes: ", b)

transpose=np.reshape(y, (25,1))
print("Transpose: ", transpose)
t=y.T
print(t)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimenions of the array:  1
Shape of the array:  (25,)
Total elements in the array: 25
Data type:  float64
Total number of bytes:  200
Transpose:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [27]:
ucs420=([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
m1=np.mean(ucs420)
print("Mean: ", m1)

m2=np.median(ucs420)
print("Median: ", m2)

m3=np.max(ucs420)
print("Maximum: ", m3)

m4=np.min(ucs420)
print("Minimum: ", m4)

u=np.unique(ucs420)
print("Unique elements: ", u)

r1=np.reshape(ucs420, (4,3))
print("Reshaped array: ", r1)

r2=np.resize(ucs420, (2,3))
print("Resized array: ", r2)


Mean:  43.333333333333336
Median:  37.5
Maximum:  90
Minimum:  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:  [[10 20 30]
 [40 50 60]]
